Fix input deduplication e.g. two entries for one gene
Used to error out when we had duplicate rows that were not in the
network

Error: `ValueError: cannot reindex from a duplicate axis`
On line: `node2attribute = node2attribute.reindex(index=node_label_order, fill_value=fill_value)`

Example input from AFT1 Yeast TF data from IDEA, modified to include duplicate entries:

ORF     Value
YMR056C -0.792311525
YMR056C -0.019015263
YMR056C -0.83412795
YMR056C -0.471975731
YNR016C -0.21730749
YBL015W -0.915305609
YLR304C -1.591613527
YJL200C -1.624091036
YLR153C -0.736739858
etc.

Common example of input where only YBL015W and YLR153C are in the input.
YNR016C, YLR304C, and YJL200C are successfully ignored

Finally, duplicate YMR056C causes issues:
We check for duplicates via  to determine whether we should average values
but this only checks the mapped rows/nodes. Meanwhile, we try to reindex the whole array, including nodes that don't exist in the network

So if we *only* have duplicates in nodes that don't exist in the network, like YMR056C, they will not be caught by the old check.
To fix this, I change the check to
Finally, I also noticed that the  check, although working as intended
(the default node_label_order parameter [] will be evaluated as False), I changed the default parameter to None to make this more clear.